 platform:ios,’9.0’

 target 'HuPiao' do 
 pod 'AFNetworking'
 pod 'SDWebImage'
 pod 'SVProgressHUD'
 pod 'MJExtension'
 pod 'MJRefresh'
 pod 'Masonry'
 pod 'KRVideoPlayer'
 pod 'YYImage'
 pod 'YYImage/WebP'
 pod 'YYWebImage'
 pod 'WMPageController'
 pod 'HZPhotoBrowser'
 pod 'PrintBeautifulLog'
 pod 'IQKeyboardManager'
 pod 'RealReachability'
 pod 'SDCycleScrollView'
 pod 'YNPageViewController'
 pod 'FMDB'
 pod 'YYStarView'
 pod 'BRPickerView'
 pod 'TZImagePickerController'
 pod 'FFDropDownMenu'
 pod 'WHToast'
 pod 'JShare'
 pod 'JAnalytics'
 pod 'JMessage'
 pod 'JPush'
pod 'LJXAlertView'
 end

